### ISSUE TITLE
Some types don't bind correctly (Regression in PR #11)

### ISSUE THREAD

**Issue by RoryDungan** [Real-Serious-Games/Unity-Weld#15]
PR #11 *Binding to types that cast implicitly* added the ability to convert without an adapter between types that can cast implicitly like float and double. This relies on the [`Convert.ChangeType`](https://docs.microsoft.com/en-au/dotnet/api/system.convert.changetype?view=netframework-4.7.1#System_Convert_ChangeType_System_Object_System_Type_) method, which assumes the value being converted implementes the [IConvertable](https://docs.microsoft.com/en-au/dotnet/api/system.iconvertible?view=netframework-4.7.1) interface. 

The problem with this is that if the value doesn't implement IConvertible the method will just throw an exception and fail. This doesn't seem to happen in the case where the type already matches the conversion type, which is why it wasn't caught previously. 

The problem occurs when converting a reference to a derived type to a reference of the type of the base class, such as converting from Texture2D to Texture. In this case, it should work without calling `Convert.ChangeType`, but because we're calling that for all values and because Texture2D doesn't implement IConvertable, it fails. 

If we can't figure out a simple solution I'm thinking we should probably revert that feature since it was a convenience and the same functionality could be achieved with adapters.

**Comment by nickludlam** [comment]
I've run into exactly this issue today with trying to set a RawImage's texture with a Texture2D instance. Would it be possible to have a separate codepath for an adapter to bypass the Convert.ChangeType call?

**Comment by RoryDungan** [comment]
I made a pull request (#18) that reverts the broken code from #11 but was waiting to merge it to see if it affects anyone else or if anyone has a better idea for a solution. I'll see if I can merge it on Monday when I'm back in the office and can get another member of the team to review it.

**Comment by RoryDungan** [comment]
Fix has been merged now. Automatic casting for types that support it (from #11) is still a useful feature so it would be good to try and work out how we can add it again, but for now you can use an adapter.

**Comment by MorganMoon** [comment]
I was able to get it working without Convert.ChangeType by using the dynamic type, however I don't think unity's default c# version supports that. 🤔 Haven't had much time to look into another solution ):
