### ISSUE TITLE
TwoWayBinding on a Slider with Min Value not set to 0 fails

### ISSUE THREAD

**Issue by marijneken** [Real-Serious-Games/Unity-Weld#20]
I've created a standard Unity UI Slider and added a TwoWayBinding component.
This works fine, until you change the Min Value on the Slider to something different than 0.

What happens is, that the view-model property that is bound to this Slider is first called with the correct value (when changing the slider). But after that it's called a second time with 'value' set to the Min Value. This isn't reflected in the UI though, so things seem to be working, when in reality they aren't.

I looked at the Call Stack for both these calls and noticed something. The first (correct) call originates from a UnityEngine.UI.Slider:OnPointerDown event. The second (incorrect) call originates from a UnityEngine.UI.Slider:OnDrag event. The value always seems to be 0 in this second call. Which is is outside the range for the Slider, so it's corrected back to Min Value.

While typing this, I tried a few more things and it seems that this second call always happens. Also when Min Value is set to 0. I can see my property's "set" being called, but somehow the correct value ends up in my private field.

I think this might not have anything to do with Unity-Weld at this point, but I'm totally confused as to what's going on here. My work around for now is to set the Min Value to 0, because then everything seems to work as expected, even though I see these weird calls with value 0 happening all the time.

**Comment by RoryDungan** [comment]
I had a go of modifying the slider example from our [example project](https://github.com/Real-Serious-Games/Unity-Weld-Examples) to use min values other than 0. 

What I observed was that moving the sliders worked as expected, and I could move one slider beyond the minimum value of the other one fine. 
![scrollbar](https://user-images.githubusercontent.com/8509978/41750964-26899184-7602-11e8-9183-b24f5a318c2e.gif)

I noticed that when I changed the value the slider was bound to externally to a value outside the range of the slider, the property would be set once with that value, then immediately again with the min value of the slider. Is this the issue you're talking about?
![scrollbar-2](https://user-images.githubusercontent.com/8509978/41750990-4acd8d8e-7602-11e8-997a-006d689def5c.gif)

**Comment by marijneken** [comment]
Thanks for the in depth tests. No, that's not the issue I'm having. I just did some more tests and I'm having a hard time debugging it.
The problem is, that this problem doesn't show up in the UI. Like your example, my slider is working fine and if I connect a Text object to it, it shows the correct value all the time.

The thing is though, in my "set" method for this property I'm also calling `PlayerPrefs.SetInt("DayOfYear", value)`. When my application is restarted, I'm reading that value back from the PlayerPrefs. And THAT'S how I discovered the problem. Somehow, my property's "set" method is called with an incorrect value, and somehow at the same time the UI doesn't reflect that wrong value. I want the range to be [1, 365], but that results in PlayerPrefs always storing the value 1 (well, it's the last value that's written). If I set the range of the slider to [0, 365], everything works as expected.

Since this incorrect value seems to come from Unity's side, I'm not sure there's anything you could do really. These are the two consecutive calls I get:
![image](https://user-images.githubusercontent.com/928998/41839721-4564ccea-7864-11e8-9974-3679062edd47.png)

![image](https://user-images.githubusercontent.com/928998/41839743-4dd4102a-7864-11e8-838b-3c4454a1a6f5.png)

That last zero gets changed into a 1 later, because it's outside the range. As you might notice, the localCursor value for the second call is a lot more to the left, compared to the first call. I noticed that this is something that happens during debugging, because I moved my mouse pointer to my screen on the left after the first breakpoint was hit. So at one point I thought that this whole problem might only occur during debugging, but that's not the case as I can see by the value that is stored by the PlayerPrefs call.

So, right now I've just decided to set the range to [0, 365] and live with it. It's pretty confusing to me why the call with this wrong value happens and how it could be that the UI is NOT showing this wrong value. Maybe I'm doing something wrong, but my code is pretty simple so I don't think it's me:

```
[Binding]
public int DayOfYear
{
    get
    {
        return dayOfYear;
    }
    set
    {
        if (dayOfYear == value)
        {
            return; // No change.
        }

        dayOfYear = value;
        PlayerPrefs.SetInt("DayOfYear", value);
        OnPropertyChanged("DayOfYear");
    }
}
```

**Comment by RoryDungan** [comment]
Hmm looks like this is the just way Unity UI works. I'll close this for now because it looks like you have a workaround and I'm not sure what we could do from our side to fix it, but let us know if you have an idea how we could better handle it.

**Comment by marijneken** [comment]
Fair enough. I also noticed that when I place an `OnPropertyChanged` call somewhere in my code to trigger a UI update, besides the "get" method, the "set" method is also called by Unity. Pretty strange and wrong behavior in my opinion.
