### ISSUE TITLE
Binding to game object visibility

### ISSUE THREAD

**Issue by realworld666** [Real-Serious-Games/Unity-Weld#21]
I want to disable some of my UI based on the value of a bool in my view model. I was hoping I would be able to bind to gameObject.active but I guess turning off the game object would disable the component so it would never turn back on. Is there a better approach?

**Comment by MorganMoon** [comment]
You can use the ToggleActiveBinding component which enables/disables it's children.

**Comment by realworld666** [comment]
That's great, thanks :)
